# Generated by Django 4.0.1 on 2022-03-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problem_model',
            fields=[
                ('ProblemId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Solution', models.URLField()),
                ('Difficulty', models.CharField(max_length=10)),
                ('Decription', models.CharField(max_length=800)),
            ],
        ),
    ]
